### ISSUE TITLE
add required libs to readme

### ISSUE THREAD

**Issue by MatthewKhouzam** [theia-ide/tsp-python-client#17]
I counted 
`pandas` , `tabulate`, `termcolor` so far

**Comment by bhufmann** [comment]
The requirement.txt should be up-to-date and users can use to install dependencies. Maybe we should describe how to install them using pip?

**Comment by marco-miller** [comment]
> The requirement.txt should be up-to-date and users can use to install dependencies. Maybe we should describe how to install them using pip?

Done through #25.
