### ISSUE TITLE
Help should display when no arguments are given

### ISSUE THREAD

**Issue by MatthewKhouzam** [theia-ide/tsp-python-client#2]
if I write `tsp-cli-client`, I would like to see:

usage: tsp-cli-client [-h] [--ip IP] [--port PORT] [--open-trace TRACE_PATH]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[--name NAME] [--list-traces] [--list-trace UUID]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[--list-outputs UUID] [--get-tree OUTPUT_ID]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[--uuid UUID]

**Comment by bhufmann** [comment]
Makes sense. Thanks for reporting this
